/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSocialImport } from './routes/_layout/social'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutReportsImport } from './routes/_layout/reports'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutCampaignsImport } from './routes/_layout/campaigns'
import { Route as LayoutAiAnalysisImport } from './routes/_layout/ai-analysis'
import { Route as LayoutAffiliatesImport } from './routes/_layout/affiliates'
import { Route as LayoutAffiliateImport } from './routes/_layout/affiliate'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSocialRoute = LayoutSocialImport.update({
  path: '/social',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsRoute = LayoutReportsImport.update({
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCampaignsRoute = LayoutCampaignsImport.update({
  path: '/campaigns',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAiAnalysisRoute = LayoutAiAnalysisImport.update({
  path: '/ai-analysis',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAffiliatesRoute = LayoutAffiliatesImport.update({
  path: '/affiliates',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAffiliateRoute = LayoutAffiliateImport.update({
  path: '/affiliate',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/affiliate': {
      preLoaderRoute: typeof LayoutAffiliateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/affiliates': {
      preLoaderRoute: typeof LayoutAffiliatesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/ai-analysis': {
      preLoaderRoute: typeof LayoutAiAnalysisImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/campaigns': {
      preLoaderRoute: typeof LayoutCampaignsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports': {
      preLoaderRoute: typeof LayoutReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/social': {
      preLoaderRoute: typeof LayoutSocialImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutAffiliateRoute,
    LayoutAffiliatesRoute,
    LayoutAiAnalysisRoute,
    LayoutCampaignsRoute,
    LayoutItemsRoute,
    LayoutReportsRoute,
    LayoutSettingsRoute,
    LayoutSocialRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
